### ISSUE TITLE
esMasRicoQue

### ISSUE THREAD

**Issue by dperezferrando** [NicoAcosta/PDEP-TPs#8]
https://github.com/NicoAcosta/PDEP-TPs/blob/1e1a8236e3d32f8c266fa91305fdb670f4da3f61/logico/tp1.pl#L22
Ojo con el orden de las clausulas aca, poniendo el not antes de viveEn el predicado deja de ser inversible. Si pones viveEn antes, por ser un hecho, es inversible y puede ligar la variable Rico para poder consultar "esMasRicoQue(X, agatha)"
En ese caso no te jode en "esAsesinoDe" porque se ligan las variables antes

Asumi que vieron inversibilidad porque está en la planificacion, si no entendiste nada avisame porque capaz no lo vieron :P

**Comment by NicoAcosta** [comment]
resuelto

`esMasRicoQue(Rico, agatha):-
    viveEnMansion(Rico),
    not(odiaA(carnicero, Rico)).`
